language: ruby
cache: bundler

rvm:
  - 2.4.0
  - 2.4.1
  - ruby-head

matrix:
  allow_failures:
  - rvm: ruby-head

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rails db:migrate

test_script:
  - rspec

after_success:
  - bundle exec codeclimate-test-reporter

notifications:
  email:
    on_success: never
    on_failure: always
